### ISSUE TITLE
Support for Play 2.6

### ISSUE THREAD

**Issue by matterche** [zalando-incubator/play-zhewbacca#35]
It would be nice to support the latest version of Play and have cross Scala versions for 2.11 and 2.12.

Unfortunately for us the missing 2.6 support is a blocker for migration to Play 2.6.

**Comment by matterche** [comment]
FYI: I just started to prepare a pull request to support pushing this topic. Will be hopefully finished today.

**Comment by dmitrykrivaltsevich** [comment]
Looks very promising!
